### ISSUE TITLE
Split Gruntfile.js into multiple config files

### ISSUE THREAD

**Issue by nessthehero** [BarkleyREI/generator-brei-app#11]
https://github.com/creynders/load-grunt-configs

Step one would be to split the existing gruntfile into multiple config files.

Step two would be to move all the split config files into their own repos and set them as dependancies, so that we can achieve the "upgradeable projects" concept.

**Comment by eightdotthree** [comment]
I was just looking at the Gruntfile and what we can get rid of, etc. Right now it's more of a rough sketch.

**Comment by JDillon522** [comment]
Nice. I feel like the turd in the punchbowl because I havent touched this. Been too busy with family, work, kids flushing things down the toilet, etc. haha

Maybe you can put your update in a gist? or even a PR for some feedback if you're at that point

**Comment by eightdotthree** [comment]
I created another issue specific to removing the bloat. I will do a pull request once I am able to pull it all out and test it.
