### ISSUE TITLE
Add trailing new line to .scss files on partial/module creation 

### ISSUE THREAD

**Issue by sharissis-brei** [BarkleyREI/generator-brei-app#115]
When generating a partial or module and the .scss file is created, it's generated without a trailing new line. Unless you add one manually for each and every partial/module, you will get this error:

[W] FinalNewline: Files should end with a trailing newline

It would be nice not to have to go through every new file one by one to add this new line.

**Comment by nessthehero** [comment]
Blegh, I thought I did this
