### ISSUE TITLE
Add string compare function to helpers

### ISSUE THREAD

**Issue by sharissis-brei** [BarkleyREI/generator-brei-app#116]
I find the following very helpful for differentiating between which partials to include in templates:

`Handlebars.registerHelper('str_compare', function(a, b, opts) {
    if (a == b)
        return opts.fn(this);
    else
        return opts.inverse(this);
});`

It's useful mastheads (image/slider/video), video types (youtube/vimeo/html5), etc.

**Comment by nessthehero** [comment]
Fork the repo and do a pull request
