### ISSUE TITLE
Split out plugins and bower_components

### ISSUE THREAD

**Issue by nessthehero** [BarkleyREI/generator-brei-app#14]
I see a use for having bower_components to store installed components and plugins via the `bower` command, whereas the `plugins` folder should contain custom written plugins or collections of dependancies not available on bower.

The main reason for the difference is that we should be saving dependancies to the bower.json file so they can be installed on project initialization, and not be committed to SVN/Git.

I don't want bower_components or node_modules to be committed to any version control. They bulk up the repo and make checking out and branching take longer than they should.

**Comment by eightdotthree** [comment]
bower components should still be installed into bower_components. Any JavaScript files downloaded independently from bower should be copied into js/plugins and ignored by JSLint.

**Comment by nessthehero** [comment]
I think this is now in the generator.
