### ISSUE TITLE
Remove unused commands

### ISSUE THREAD

**Issue by eightdotthree** [BarkleyREI/generator-brei-app#16]
We aren't using the Mocha framework, cssmin, htmlmin, concat, uglify.

**Comment by nessthehero** [comment]
Agree

**Comment by nessthehero** [comment]
Did some testing. The only things that can be safely removed are the mocha references and the empty concat and uglify task blocks. Everything else is used, including the references to htmlmin, cssmin, concat, and uglify in the task declarations at the bottom.
