### ISSUE TITLE
Update html tag conditionals

### ISSUE THREAD

**Issue by sharissis-brei** [BarkleyREI/generator-brei-app#178]
I think the html tag conditionals should be changed to the following:

```
<!--[if lt IE 7]>      <html class="no-js lt-ie10 lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie10 lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie10 lt-ie9" lang="en"> <![endif]-->
<!--[if IE 9]>         <html class="no-js lt-ie10" lang="en"> <![endif]-->
<!--[if gt IE 9]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
```

2 reasons:
1. Accessibility validators expect to see the lang attribute on the html tag.
2. I find myself targeting IE9 more and more now that we don't support IE8 for most clients, but still support IE9 for a few.

**Comment by nessthehero** [comment]
![](http://cultofthepartyparrot.com/parrots/parrot.gif)
