### ISSUE TITLE
Command Line option to disable minification

### ISSUE THREAD

**Issue by nessthehero** [BarkleyREI/generator-brei-app#18]
Sort of a "debug mode" where we can compile the assets without minifying them, in order to debug issues where we need to see the exact line of code causing the issue.

Current option is to manually disable minification with code changes to the grunt file.

**Comment by JDillon522** [comment]
This is a good idea. We can do this for other tasks as well.

http://gruntjs.com/api/grunt.option

**Comment by nessthehero** [comment]
I would like something where you can toggle debug on or off. They show that in the grunt.option example you posted, and we could have a task like `grunt debug:on` and `grunt debug:off` to toggle the state.

Would need to add messaging to make it obvious that debug mode is on, but ideally, debug mode would not minify assets or strip any debug code out.

**Comment by nessthehero** [comment]
Figured out a way to do this with nconf
