### ISSUE TITLE
Add helper .sccs file for Google Search overrides

### ISSUE THREAD

**Issue by sharissis-brei** [BarkleyREI/generator-brei-app#183]
I suggest adding a file in the helpers for overwriting Google Search styles. Ideally, the file would also be configured to be exempt from scsslint so we can use things like !important, etc.

**Comment by nessthehero** [comment]
I'm gonna move this to the sass boilerplate repo.

**Comment by nessthehero** [comment]
This issue was moved to BarkleyREI/brei-sass-boilerplate#44
