### ISSUE TITLE
Integrate Require.js into Build

### ISSUE THREAD

**Issue by nessthehero** [BarkleyREI/generator-brei-app#20]

**Comment by dtm5011** [comment]
http://browserify.org/

**Comment by JDillon522** [comment]
Going to move this to 2.2.0 because I really want to keep 2.1.0 stuff everything we need for stability and immediate development.

**Comment by nessthehero** [comment]
Might no longer be required if we can write ES6 modules.

**Comment by nessthehero** [comment]
Scrapped for Gulp Generator.
