### ISSUE TITLE
Missing meta description tag

### ISSUE THREAD

**Issue by sharissis-brei** [BarkleyREI/generator-brei-app#259]
Aaron just approached me about an issue with Curry's SEO. If you search "uva curry" on Google, you get the following: "Jump to Header Jump to Masthead Jump to Impact Stories Section Jump to Make Your Mark Section Jump to Opportunity Abounds Section Jump to Footer." This is because we are missing a meta description tag.

To avoid this miss in the future, we should add a meta description tag to _meta.hbs in the generator.

**Comment by nessthehero** [comment]
We can add a description tag to the assemble structure repo, but it's ultimately the integrator who has to make sure that the description tag is properly generated.
