### ISSUE TITLE
npm install -g generator-brei-app doesn't install the generator

### ISSUE THREAD

**Issue by eightdotthree** [BarkleyREI/generator-brei-app#37]
When I run npm install -g generator-brei-app or attempt to instal using Yeoman's guided search and install, Yeoman can't find the generator. No errors are thrown. The `yo doctor` tests return fine.

**Comment by nessthehero** [comment]
interesting...

**Comment by nessthehero** [comment]
Fixed. Problem was that package.json was not referencing the "generators" directory under "files".
