### ISSUE TITLE
TravisCI Build for Master fails

### ISSUE THREAD

**Issue by nessthehero** [BarkleyREI/generator-brei-app#44]
=(

**Comment by JDillon522** [comment]
This is pissing me off. 

Its failing when it tries to fetch a remote repo when the main app is generated. Most of the time it fails for the brei-assemble-structure, but sometimes for the helpers. 

I've reran the build a number of times and multiple times it comes back as passing. When I come back to check it again it suddenly says its failing. Aaaahhh!! 

I have no idea :P I think we just need to let it sit until [their status](http://www.traviscistatus.com/) is back to green. Right now they have degraded github service which might account for the partial failure of them being able to pull another repo into the generator. 

Eff

**Comment by JDillon522** [comment]
I added a couple of console logs for when things error. It looks like its getting a 404 when it tries to get the repos. Might be connected to degraded GitHub service, or not.

**Comment by JDillon522** [comment]
I am awesome! 

So, I poked around at the api docs for yeoman and took a gander at [remote() helper](http://yeoman.github.io/generator/remote.html). I then took a look at the [source code](http://yeoman.github.io/generator/remote.js.html#line50).

The breakthrough was [this line](http://yeoman.github.io/generator/remote.js.html#line77):
`url = 'http://github.com/' + [username, repo, 'archive', branch].join('/') + '.tar.gz';`

I realized that it was looking for a tagged release. None of our other repos had releases so it was returning 404. 

I created a release for each and now we're rocking with [Travis](https://travis-ci.org/BarkleyREI/generator-brei-app)! Boom baby!
