### ISSUE TITLE
Add namespaced JavaScript

### ISSUE THREAD

**Issue by eightdotthree** [BarkleyREI/generator-brei-app#51]
When generating a new project ask for a namespace or generate it based on the project name. Create main.js and level.js. 

A sub-generator could be made to generate new JavaScript files using the namespace.

**Comment by nessthehero** [comment]
@Sean-BREI is whipping up a boilerplate to use

**Comment by nessthehero** [comment]
Might be moot if @Sean-BREI implements ES6 and Babel

**Comment by Sean-BREI** [comment]
If we are able to successfully use ES6 modules and export/import logic then namespacing won't be necessary.

**Comment by nessthehero** [comment]
Scrapped for Gulp Generator.
