### ISSUE TITLE
Add tests for build tasks

### ISSUE THREAD

**Issue by JDillon522** [BarkleyREI/generator-brei-app#52]
We dont have tests for grunt tasks. I'm not sure how to do this but we need them. Especially for `grunt build` and `grunt server`

**Comment by nessthehero** [comment]
For `build` it might be easy to just check if everything is in the dist folder after `grunt` is run.

Server might be harder, as I don't know how you would check if livereload is running.

**Comment by nessthehero** [comment]
Not sure if this is possible. I am having difficulty running grunt tasks in the unit test. It times out before it can get to the test and I'm not even sure if it's installing the dependencies. I might move this out of milestones completely until we can figure out a way to actually do this.

**Comment by nessthehero** [comment]
I have had a breakthrough success. I am able to run grunt after setting up the generator in the tests now. I can definitely make this happen now.

- [ ] Run grunt from test suite
- [ ] Have generator accept specific answers to avoid ../../web in the deploy directory
- [ ] Write tests to validate dist directory
- [ ] Write tests to validate web directory

**Comment by nessthehero** [comment]
Having some issues with TravisCI running the tests. I reached out to TravisCI support for help.
