### ISSUE TITLE
Auto generate aliases 

### ISSUE THREAD

**Issue by JDillon522** [BarkleyREI/generator-brei-app#56]
We're getting to have a lot of sub generators and other functionality. I think it would be nice if we found a way to auto generate aliases for everyone to use.

So instead of typing:
```bash
yo brei-app:module
```
You could type:
```bash
reiMod
```

**Comment by nessthehero** [comment]
Wouldn't it be a huge security risk if an external program could set an alias? Like you could hijack `git` and make it do something else pretty easily.

I think this is a "nice-to-have" but not a super priority. I'd rather people just know how to use the generator.

It's also easy to type `yo` and follow the prompts.

**Comment by JDillon522** [comment]
Yeah this has since become much less of an issue now that you can access all the options by just doing yo or yo brei-app. Theres no need to remember all the others
