### ISSUE TITLE
Identifier in handlebars template to prevent generation of a SCSS file

### ISSUE THREAD

**Issue by nessthehero** [BarkleyREI/generator-brei-app#67]
In an inverse of #64, it may be a good idea to flag a handlebars file to not generate a SASS file.

Would help prevent a lot of cruft or unnecessary files. I don't know if Compass strips out empty selectors but it might confuse coders if modules and partials have the same name and generate two files, but only one actually has code in it.

**Comment by JDillon522** [comment]
poked around and found out that compass does not compile empty tags. I think that even if a file isnt used, it needs to exist for consistency's sake. 

However, to avoid name conflicts for events like a module and partial having the same name, we could append a "-p" or an "-m" to the respective partial or modules.

**Comment by nessthehero** [comment]
They won't name conflict because modules have an underscore prefix. The confusion is more of which file actually has code in it. That's not always intuitive in a code editor and you might keep opening the wrong file.

I dunno, maybe we can put this off a bit and see if it remains an issue. It was just a brain fart I had.
