### ISSUE TITLE
Change generated project paths

### ISSUE THREAD

**Issue by JDillon522** [BarkleyREI/generator-brei-app#69]
So currently when you create a project it dumps it into the directory you're in. But a number of projects recently had to move things post generation to `src/static/`. We should also create the `web` directory on generation. 

So yeah, I'm thinking of this:

```
/web
/src
 |_/static
 |   |_/app
 |   |_ <gruntfile, package.json, etc>
 |_/design
```

This should help east initial commit conflict shenanigans.

**Comment by nessthehero** [comment]
This structure is basically the defacto standard for Git based projects, similar to the SVN structure on Confluence. I generally agree, though I have always been activating the generator inside the `static` directory ever since the generator was created.

**Comment by JDillon522** [comment]
Yeah, I dont mind the structure, it just seems like its the way we do things here. If we want to change it thats cool too. I just dont like manually creating folders and moving things around or whatnot right off the bat.

**Comment by nessthehero** [comment]
Maybe an option via inquire.js to generate a full project structure? Wouldn't be hard.

**Comment by nessthehero** [comment]
Moved this to a different issue. I want to change the idea behind it but preserve this issue's history.
