### ISSUE TITLE
yo brei-app:template generates 2 SCSS files and confuses SASS compiler

### ISSUE THREAD

**Issue by sharissis-brei** [BarkleyREI/generator-brei-app#72]
When running yo brei-app:template, 2 SCSS files are generated – one with an underscore prefix and one without. This causes a SASS compilation error because it doesn't know which file to import. Below is an example of the error thrown after running the generator command and then running "grunt server --force":

"Error: It's not clear which file to import for '@import "faculty-staff-detail"'.
Candidates:
_faculty-staff-detail.scss
faculty-staff-detail.scss
Please delete or rename all but one of these files."

**Comment by JDillon522** [comment]
run an yo brei-app:update and update your assemble helpers. I think @nessthehero and I fixed that one.

**Comment by nessthehero** [comment]
Yeah, this is fixed in the latest updateSass.js file in the assemble helpers.
