### ISSUE TITLE
Update template and module names

### ISSUE THREAD

**Issue by JDillon522** [BarkleyREI/generator-brei-app#73]
Update things so that names [here](https://github.com/BarkleyREI/generator-brei-app/blob/master/generators/module/templates/module.hbs#L2) and [here](https://github.com/BarkleyREI/generator-brei-app/blob/master/generators/template/templates/template.hbs#L2) are pretty. 

ie. instead of "_module-name" you'll have "Module Name". 

That'll make the `index.hbs` file more pretty.

**Comment by nessthehero** [comment]
+1
